#### if we want to create a 0D tensor/scalar we will have to use numpy's array function!





In [ ]:
import numpy as np


In [ ]:
a=np.array(2)

In [ ]:
a

array(2)

In [ ]:
a.ndim

0

In [ ]:
b=np.array([2,3,4,5])

In [ ]:
b.ndim

1

In [ ]:
b

array([2, 3, 4, 5])

In [ ]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
c.ndim

2

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
d.ndim

3

In [ ]:
e=np.array([3,5,6])

In [ ]:
e.shape

(3,)

In [ ]:
e

array([3, 5, 6])